[tool.commitizen]
name = "cz_customize"
tag_format = "v$major.$minor.$patch"
version_scheme = "semver"
version = "3.2.15"
update_changelog_on_bump = true

[tool.commitizen.customize]
schema = "<type>[(scope)]: <message>"
schema_pattern = "^(break|feat|fix|docs|chore)(\\([^()\\r\\n]+\\))?(!)?:\\s.*"
bump_pattern = "^(break|feat|fix|chore)"
bump_map = { "break" = "MAJOR", "feat" = "MINOR", "fix" = "PATCH", "chore" = "PATCH" }
commit_parser = "^(?P<change_type>feat|fix|break|docs|chore)(?:\\((?P<scope>[^()\\r\\n]*)\\))?(?P<breaking>!)?:\\s(?P<message>.*)?"
changelog_pattern = "^(break|feat|fix|chore|docs)"
change_type_order = [
  "⚠️ Breaking Change",
  "🚀 New Feature",
  "🧹 Chore",
  "🐛 Fix",
  "📚 Documentation",
]

[tool.commitizen.customize.change_type_map]
break = "⚠️ Breaking Change"
feat = "🚀 New Feature"
chore = "🧹 Chore"
fix = "🐛 Fix"
docs = "📚 Documentation"
